// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADKifQ-kGPQO7uBaHuppvht9EyxrAoA_4',
    appId: '1:949582911912:web:4f090567c60da43ee8659d',
    messagingSenderId: '949582911912',
    projectId: 'rental-system-app',
    authDomain: 'rental-system-app.firebaseapp.com',
    storageBucket: 'rental-system-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpRDMODuTS4OdKUjII4IBRrDiCB3rs2ug',
    appId: '1:949582911912:android:3f4b5cd735e7bb62e8659d',
    messagingSenderId: '949582911912',
    projectId: 'rental-system-app',
    storageBucket: 'rental-system-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADKifQ-kGPQO7uBaHuppvht9EyxrAoA_4',
    appId: '1:949582911912:web:6c1a9a8f6b7fa6c7e8659d',
    messagingSenderId: '949582911912',
    projectId: 'rental-system-app',
    authDomain: 'rental-system-app.firebaseapp.com',
    storageBucket: 'rental-system-app.appspot.com',
  );

}